class League < ApplicationRecord
  has_many :teams, :dependent => :destroy


  def add_teams
    team_names = names.shuffle
    12.times do |i|
      self.teams.create!(name: "#{team_names[i]}")
    end
  end

  def names
    ['13 Reasons Ajayi',
      '99 Problems But a Fitz Ain’t One',
      'A Gronking in December',
      'Abdullah Oblongata',
      'Ain’t No Such Thing as Halfway Cooks',
      'Ajayi Another Day',
      'Al Hurns and Gurley',
      'All About the Benjamins',
      'All I Do is Winston',
      'All That I Snead',
      'All You Snead is Love',
      'Alshon of the Dead',
      'Amari 2600',
      'Amari Teenage Riot',
      'Baby Got Dak',
      'Bad and BouBrees',
      'Bilal Weve Got',
      'Blount Force Trauma',
      'Blountsprout and Ivorysaur',
      'Boldin the Beautiful',
      'Boom Boom Powell',
      'Born to Maclin',
      'Bortles Service',
      'Brees the Sheriff',
      'Bringin’ the Woodhead',
      'Can You Diggs It?',
      'Cant Stop the Thielen',
      'Christian Missionaries',
      'Chronicles of Riddick',
      'Clam Crowder',
      'Cobb Deep',
      'Crowella du Ville',
      'Czar of the Martellustrator',
      'Dak and Yellow',
      'Dakstreets Back',
      'Daltons Abbey',
      'Dandy Merediths',
      'Death Ertz-tificate',
      'Demaryius Had A Little Lamb',
      'Deshaun of the Dead',
      'DeVante’s Inferno',
      'Dez Dispensers',
      'Diggs in a Blanket',
      'Dirty Landry',
      'Dont Eli To My Face',
      'Dude Wheres My Carr?',
      'Dude Youre Getting O-Dell!',
      'Eastbound and Brown',
      'El Gordo Y La Flacco',
      'Ezekiel 25:17',
      'Fanatical Christians',
      'FartSmellus Buttnutt',
      'Fleener Than a Junkyard Dog',
      'Floyd Rage',
      'For the Winston',
      'Fournettecation',
      'Frankly Ameer I Dont Give a Damn',
      'Games of Jones',
      'Get Your Tyreek On',
      'Giovani Vidi Vici',
      'Golden Grahams',
      'Golden McCaffrey',
      'Gone Gurley',
      'Gore Values',
      'Gould Members',
      'Green Eggs and Beckham',
      'Green Initiative',
      'Gym, Tannehill, Landry',
      'Here’s My Number, So Call Me Brady',
      'Highway to Bell',
      'Honeybaked Beckham',
      'Hooked on a Thielen',
      'Hot Lockett',
      'Hurns Notice',
      'Hyde and Go Luck Yourself',
      'Hyde and Tyreek',
      'I Gotta Thielen',
      'Ill Make You Jameis',
      'Ingram Toenails',
      'InstaGraham',
      'It’s Von Like Donkey Kong',
      'Jamaal About That Bass',
      'Johnson and More Johnson',
      'Just Say Wentz',
      'Keenan-Ivory-Dwaynes',
      'Keep Choppin’ Woodhead',
      'Kelce Lately',
      'Kissing Cousins Good-bye',
      'Kizer Wide Shut',
      'Lacy Underalls',
      'Ladies and Edelman',
      'Lamar the Merrier!',
      'Lamar You Serious?',
      'Land of the Freeman',
      'Landry Service',
      'LeVeon a Prayer',
      'Let Sleeping Dogs Eli',
      'Lets Get Riddickulous!',
      'Make Demaryica Great Again!',
      'Mariota Had a Little Lamb',
      'Mariota Kart',
      'Marshawn of the Dead',
      'Martellus All About It',
      'MegaErtz',
      'Mercedes Wentz',
      'Miller’s Bossin’',
      'More than a Thielen',
      'Mr. Rodgers Neighborhood',
      'O-Dell No',
      'Palmer? I Hardly Know Her!',
      'Peachy Keenan',
      'Pimpin Aint Breesy',
      'Pocket Lockett',
      'Pop-Lockett-Drop It',
      'Poppin Bortles',
      'Praise the Jord-y',
      'Rage Against the Vereen',
      'Rawls Royces',
      'Rebel Yeldons',
      'Reeding Rainbow',
      'Roethlisberger Helper',
      'Rudolph the Red-Zone Reindeer',
      'Sanu Jack City',
      'Saving Matt Ryan',
      'Scobee Snacks',
      'Serial Miller',
      'Shadys Gurley Party',
      'Sims City',
      'Song of Matty Ice and Fire',
      'Special Zay',
      'Stacked Deckers',
      'Staff Infection',
      'Stairway to Evans',
      'Steady Cams',
      'Steady Cobbin’',
      'Sterling SilverWare',
      'Suh-and-a-Half Men',
      'Suh-Tang Clan (Aint Nuthing Ta F Wit)',
      'T.Y. Dolla $ign',
      'T.Y. Very Much',
      'Take em to the Woodhead',
      'Tate is Enough',
      'Tate Misbehavin',
      'Thats Bilal Folks!',
      'The Backfields & McCoys',
      'The Big Gronkowski',
      'The Black Crowells',
      'The Counting Crowells',
      'The Gurley Gates',
      'The Hauschka Always Wins',
      'The Jeremy Hills Have Eyes',
      'The Mixon Administration',
      'The Tannehills Have Eyes',
      'Thielen Like Makin Love',
      'To Be Prosise',
      'Touchdown Breesus',
      'Turn Down for Watkins',
      'Turn Down for Watt',
      'Turn Goff the Lights',
      'Upper Deckers',
      'View From Lamar',
      'Ware Bears',
      'We’re Allen this Together',
      'Wings of a Davante',
      'Winning is My Forte',
      'Yippee Ki Yay Justin Tucker',
      'You Know You Gano Lose',
      'Your Brate Is Sealed',
      'Zeke Squad']
    end

end
